import os
import json
from PySide6.QtWidgets import QComboBox

def get_available_devices(incident_path, data_type="spot"):
    """
    Fetches unique device labels based on the data type.
    - Spot: reads from spot_locations.json (readings arrays)
    - Area: reads from meta/devices.json (generated by importer)
    """
    devices = set()
    if not incident_path:
        return []
        
    if data_type == "spot":
        # Spot devices come from spot_locations.json
        json_path = os.path.join(incident_path, "mapping", "spot_locations.json")
        if os.path.exists(json_path):
            try:
                with open(json_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    for loc in data.get("maps", {}).get("locations", []):
                        for marker in loc.get("markers", []):
                            for entry in marker.get("readings", []):
                                device = entry.get("device")
                                if device:
                                    devices.add(str(device).strip())
            except Exception:
                pass
    else:
        # Area devices come from the importer-generated devices.json
        json_path = os.path.join(incident_path, "meta", "devices.json")
        if os.path.exists(json_path):
            try:
                with open(json_path, 'r', encoding='utf-8') as f:
                    devices.update(json.load(f))
            except Exception:
                pass

    # Final fallback to static area_devices.json if nothing was found
    if not devices:
        current_dir = os.path.dirname(os.path.abspath(__file__))
        static_path = os.path.normpath(os.path.join(current_dir, '..', 'static', 'lists', 'area_devices.json'))
        if os.path.exists(static_path):
            try:
                with open(static_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    for d in data.get("devices", []):
                        label = d.get("label")
                        if label:
                            devices.add(str(label).strip())
            except Exception:
                pass
                
    return sorted(list(devices))


def get_available_locations(incident_path, data_type="spot"):
    """
    Fetches unique marker labels from spot_locations.json or area_locations.json.
    """
    locations = set()
    if not incident_path:
        return []
        
    filename = "spot_locations.json" if data_type == "spot" else "area_locations.json"
    json_path = os.path.join(incident_path, "mapping", filename)
    
    if os.path.exists(json_path):
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for loc in data.get("maps", {}).get("locations", []):
                    for marker in loc.get("markers", []):
                        label = marker.get("label")
                        if label:
                            locations.add(str(label).strip())
        except Exception:
            pass
            
    return sorted(list(locations))


class DeviceComboBox(QComboBox):
    """Custom QComboBox that automatically loads and populates devices."""
    # Note: Defaults to "area" because the standalone dialogs (Battery, GPS, etc.) are strictly for Area data
    def __init__(self, incident_path=None, data_type="area", parent=None):
        super().__init__(parent)
        self.setEditable(True)
        self.setMinimumWidth(200)
        self.setMinimumHeight(28)
        self.load_devices(incident_path, data_type)
        
    def load_devices(self, incident_path, data_type="area"):
        """Loads devices into the combo box."""
        devices = get_available_devices(incident_path, data_type)
        self.clear()
        if devices:
            self.addItems(devices)
